<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="ADMIN-PC" failures="1" tests="1" name="Classes.Duplicate" time="37.663" errors="0" timestamp="16 Nov 2020 11:17:52 GMT">
  <testcase classname="Classes.Duplicate" name="registration" time="37.663">
    <failure message="C://Users//ADMIN//Desktop//Supriya//Test Data//sikulifilename.png: (88x26) in R[0,0 1280x1024]@S(0)" type="org.sikuli.script.FindFailed">
      <![CDATA[FindFailed: C://Users//ADMIN//Desktop//Supriya//Test Data//sikulifilename.png: (88x26) in R[0,0 1280x1024]@S(0)
  Line 2222, in file Region.java

	at org.sikuli.script.Region.wait(Region.java:2222)
	at org.sikuli.script.Region.wait(Region.java:2240)
	at org.sikuli.script.Region.getLocationFromTarget(Region.java:3188)
	at org.sikuli.script.Region.click(Region.java:3806)
	at org.sikuli.script.Region.click(Region.java:3782)
	at Classes.Duplicate.registration(Duplicate.java:70)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- registration -->
</testsuite> <!-- Classes.Duplicate -->
